apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vattsopheak-xyz-tls
spec:
  secretName: vattsopheak-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vattsopheak.xyz
  dnsNames:
    - vattsopheak.xyz
    - www.vattsopheak.xyz
